server {
    listen       80;
    server_name  localhost;

    # 1. 处理前端的 React 静态页面
    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # 2. 拦截所有 /api/ 开头的请求，偷偷转发给后端容器 (反向代理核心！)
    location /api/ {
        # 这里的 'backend' 就是我们在 docker-compose 里给后端起的名字
        proxy_pass http://backend:8123/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }
}